import Footer from '~/components/Footer'
import './globals.css'
import { TrpcProvider } from '~/utils'
import Sidebar from '~/components/Sidebar'
import Header from '~/components/Header'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const theme = cookies().get('theme')

  return (
    <ClerkProvider>
      <html lang="en" className={theme?.value}>
        <body className={inter.className}>
          <TrpcProvider>
            <div className="">
              <Sidebar />
              <div className="">
                <Header />
                {children}
                <Footer />
              </div>
            </div>
          </TrpcProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
