version: '3.3'
services:
  mongo:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  mongo:
  redis:

