// export * from './postById.schema'
export * from './postAll.schema'
export * from './postNew.schema'
export * from './postLike.schema'
export * from './postId.schema'
export * from './postEdit.schema'
